### ISSUE TITLE
Need a .Net Standard version of this package

### ISSUE THREAD

**Issue by Korporal** [Brightspace/valence-sdk-dotnet-restsharp#8]
We have code that relies on D2L.Extensibility.AuthSdk.Restsharp and that in turn relies on D2L.Extensibility.AuthSdk.

Is it possible to create a .Net Standard version nuget package for D2L.Extensibility.AuthSdk.Restsharp? because we also use RestSharp in a .Net Standard version and we get all kinds of concflicts.

**Comment by j3parker** [comment]
v1.2.0 targets .NET Standard 2.0.

**Comment by The-Futurist** [comment]
@j3parker - Many thanks.
